<?php
$this->headTitle()->append($this->translate('Contact'));
$this->headMeta()->appendName('description', 'Contact form for sending message to me.');

echo '<h2>' . $this->translate('Contact') . '</h2>';

if (isset($this->contact)) {
    /** @var \MamuzContact\Entity\Contact $contact */
    $contact = $this->contact;
    echo $this->alert($this->translate('Thank you for sending message.'), 'alert-success');
    echo '<h2><small>' . $this->translate('Summary') . '</small></h2>';
    echo '<dl class="dl-horizontal">';
    foreach ($contact->toArray() as $field => $value) {
        echo '<dt>' . $this->translate($field) . '</dt>';
        echo '<dd>' . nl2br($this->escapeHtml($value)) . '</dd>';
    }
    echo '</dl>';
} else {
    $notice = 'Please note, that I will not respond to recruiters,<br />'
        . ' nor to questions that could be asked in public forums.';
    echo '<p>' . $this->translate($notice) . '</p>';
    /** @var \Zend\Form\Form $form */
    $form = $this->form;
    $form->setAttribute('action', $this->url('contact'));
    $form->prepare();

    echo '<div class="well bs-component">';
    echo $this->form($form);
    echo '</div>';
}
