<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contact\Service\Command'                                  =>
    __DIR__ . '/../module/Contact/src/Contact/Service/Command.php',
    'Contact\Service\CommandFactory'                           =>
    __DIR__ . '/../module/Contact/src/Contact/Service/CommandFactory.php',
    'Contact\Mapper\Db\Command'                                =>
    __DIR__ . '/../module/Contact/src/Contact/Mapper/Db/Command.php',
    'Contact\Feature\CommandInterface'                         =>
    __DIR__ . '/../module/Contact/src/Contact/Feature/CommandInterface.php',
    'Contact\Form\CreateFactory'                               =>
    __DIR__ . '/../module/Contact/src/Contact/Form/CreateFactory.php',
    'Contact\Entity\Contact'                                   =>
    __DIR__ . '/../module/Contact/src/Contact/Entity/Contact.php',
    'Contact\Controller\CommandControllerFactory'              =>
    __DIR__ . '/../module/Contact/src/Contact/Controller/CommandControllerFactory.php',
    'Contact\Controller\CommandController'                     =>
    __DIR__ . '/../module/Contact/src/Contact/Controller/CommandController.php',
    'ContactTest\Bootstrap'                                    => __DIR__ . '/../module/Contact/test/Bootstrap.php',
    'ContactTest\Service\CommandFactoryTest'                   =>
    __DIR__ . '/../module/Contact/test/ContactTest/Service/CommandFactoryTest.php',
    'ContactTest\Service\CommandTest'                          =>
    __DIR__ . '/../module/Contact/test/ContactTest/Service/CommandTest.php',
    'ContactTest\Mapper\Db\CommandTest'                        =>
    __DIR__ . '/../module/Contact/test/ContactTest/Mapper/Db/CommandTest.php',
    'ContactTest\Form\CreateFactoryTest'                       =>
    __DIR__ . '/../module/Contact/test/ContactTest/Form/CreateFactoryTest.php',
    'ContactTest\Entity\ContactTest'                           =>
    __DIR__ . '/../module/Contact/test/ContactTest/Entity/ContactTest.php',
    'ContactTest\Controller\CommandControllerFactoryTest'      =>
    __DIR__ . '/../module/Contact/test/ContactTest/Controller/CommandControllerFactoryTest.php',
    'ContactTest\Controller\CommandControllerTest'             =>
    __DIR__ . '/../module/Contact/test/ContactTest/Controller/CommandControllerTest.php',
    'Contact\Module'                                           => __DIR__ . '/../module/Contact/Module.php',
    'Application\Service\LogFactory'                           =>
    __DIR__ . '/../module/Application/src/Application/Service/MailFactory.php',
    'Application\Service\ErrorHandlingFactory'                 =>
    __DIR__ . '/../module/Application/src/Application/Service/ErrorHandlingFactory.php',
    'Application\Service\ErrorHandling'                        =>
    __DIR__ . '/../module/Application/src/Application/Service/ErrorHandling.php',
    'Application\Service\Mail'                                 =>
    __DIR__ . '/../module/Application/src/Application/Service/Mail.php',
    'Application\Listener\Aggregate'                           =>
    __DIR__ . '/../module/Application/src/Application/Listener/Aggregate.php',
    'Application\Controller\IndexController'                   =>
    __DIR__ . '/../module/Application/src/Application/Controller/IndexController.php',
    'ApplicationTest\Listener\AggregateTest'                   =>
    __DIR__ . '/../module/Application/test/ApplicationTest/Listener/AggregateTest.php',
    'ApplicationTest\Controller\IndexControllerTest'           =>
    __DIR__ . '/../module/Application/test/ApplicationTest/Controller/IndexControllerTest.php',
    'ApplicationTest\Bootstrap'                                => __DIR__ . '/../module/Application/test/Bootstrap.php',
    'Application\Module'                                       => __DIR__ . '/../module/Application/Module.php',
    'ContentManager\Service\Query'                             =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Service/Query.php',
    'ContentManager\Service\QueryFactory'                      =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Service/QueryFactory.php',
    'ContentManager\Mapper\Db\Query'                           =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Mapper/Db/Query.php',
    'ContentManager\Feature\QueryInterface'                    =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Feature/QueryInterface.php',
    'ContentManager\Entity\NullPage'                           =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Entity/NullPage.php',
    'ContentManager\Entity\Page'                               =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Entity/Page.php',
    'ContentManager\Controller\QueryControllerFactory'         =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Controller/QueryControllerFactory.php',
    'ContentManager\Controller\QueryController'                =>
    __DIR__ . '/../module/ContentManager/src/ContentManager/Controller/QueryController.php',
    'ContentManagerTest\Bootstrap'                             =>
    __DIR__ . '/../module/ContentManager/test/Bootstrap.php',
    'ContentManagerTest\Service\QueryTest'                     =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Service/QueryTest.php',
    'ContentManagerTest\Service\QueryFactoryTest'              =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Service/QueryFactoryTest.php',
    'ContentManagerTest\Mapper\Db\QueryTest'                   =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Mapper/Db/QueryTest.php',
    'ContentManagerTest\Entity\NullPageTest'                   =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Entity/NullPageTest.php',
    'ContentManagerTest\Entity\PageTest'                       =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Entity/PageTest.php',
    'ContentManagerTest\Controller\QueryControllerFactoryTest' =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Controller/QueryControllerFactoryTest.php',
    'ContentManagerTest\Controller\QueryControllerTest'        =>
    __DIR__ . '/../module/ContentManager/test/ContentManagerTest/Controller/QueryControllerTest.php',
    'ContentManager\Module'                                    => __DIR__ . '/../module/ContentManager/Module.php',
);
