<h1>Contact</h1>
<?php
if (isset($this->contact)) {
    /** @var \Contact\Entity\Contact $contact */
    $contact = $this->contact;
    echo $this->alert('Thank you for sending message.', 'alert-success');
    echo '<h2><small>Summary</small></h2>';
    echo '<dl class="dl-horizontal">';
    foreach ($contact->toArray() as $field => $value) {
        echo '<dt>' . $field . '</dt><dd>' . nl2br($this->escapeHtml($value)) . '</dd>';
    }
    echo '</dl>';
} else {
    /** @var \Zend\Form\Form $form */
    $form = $this->form;
    $form->setAttribute('action', $this->url('contact'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->form($form);
    echo $this->form()->closeTag();
}
