<div class="infinite-scroll">
    <?php
    foreach ($this->collection as $entity) {
        /** @var \Blog\Entity\Post $entity */
        $url = $this->url(
            'blogActivePost',
            array(
                'title' => $entity->getTitle(),
                'id'    => $this->hashId($entity->getId())
            )
        );
        echo '<h2><a href="' . $url . '">' . $entity->getTitle() . '</a></h2>' . PHP_EOL;
        echo '<p>' . $entity->getContent() . '</p>' . PHP_EOL;
    }
    ?>
</div>
<?php
echo $this->pager($this->collection, 'blogActivePosts', array('page' => $this->currentPage));
