language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer update

script:
  - cd ./test; phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
