<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type" : "Person",
    "name" : "Marco Muths",
    "url" : "http://www.mamuz.de",
    "logo": "http://www.mamuz.de/img/mamuz.png"
    "sameAs" : [
        "https://www.linkedin.com/in/mamuz",
        "https://www.xing.com/profile/Marco_Muths",
        "https://twitter.com/mamuz_de",
        "http://stackoverflow.com/users/2342306/mamuz"
    ]
}
</script>
