<?php

/** @var \MamuzBlog\Entity\Post $post */
$post = $this->post;

$this->headMeta()->setProperty('og:type', 'article');
$this->headMeta()->setProperty('og:author', 'Marco Muths');
$this->headMeta()->setProperty('og:url', $this->permaLinkPost($this->post));
$this->headMeta()->setProperty('og:site_name', 'mamuz\' coding blog');
$this->headMeta()->setProperty('og:locale', 'en_US');
$this->headMeta()->setProperty('og:title', $post->getTitle());
$this->headMeta()->setProperty('og:description', $post->getDescription());
$this->headMeta()->setProperty('article:published_time', $post->getCreatedAt()->format('c'));
$this->headMeta()->setProperty('article:modified_time', $post->getModifiedAt()->format('c'));
