<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contact\Service\Command'                             => __DIR__ . '/src/Contact/Service/Command.php',
    'Contact\Service\CommandFactory'                      => __DIR__ . '/src/Contact/Service/CommandFactory.php',
    'Contact\Mapper\Db\Command'                           => __DIR__ . '/src/Contact/Mapper/Db/Command.php',
    'Contact\DomainManager\ProviderInterface'             =>
    __DIR__ . '/src/Contact/DomainManager/ProviderInterface.php',
    'Contact\DomainManager\Factory'                       => __DIR__ . '/src/Contact/DomainManager/Factory.php',
    'Contact\Feature\CommandInterface'                    => __DIR__ . '/src/Contact/Feature/CommandInterface.php',
    'Contact\Form\CreateFactory'                          => __DIR__ . '/src/Contact/Form/CreateFactory.php',
    'Contact\Entity\Contact'                              => __DIR__ . '/src/Contact/Entity/Contact.php',
    'Contact\Controller\CommandControllerFactory'         =>
    __DIR__ . '/src/Contact/Controller/CommandControllerFactory.php',
    'Contact\Controller\CommandController'                => __DIR__ . '/src/Contact/Controller/CommandController.php',
    'ContactTest\Bootstrap'                               => __DIR__ . '/test/Bootstrap.php',
    'ContactTest\Service\CommandFactoryTest'              =>
    __DIR__ . '/test/ContactTest/Service/CommandFactoryTest.php',
    'ContactTest\Service\CommandTest'                     => __DIR__ . '/test/ContactTest/Service/CommandTest.php',
    'ContactTest\Mapper\Db\CommandTest'                   => __DIR__ . '/test/ContactTest/Mapper/Db/CommandTest.php',
    'ContactTest\Form\CreateFactoryTest'                  => __DIR__ . '/test/ContactTest/Form/CreateFactoryTest.php',
    'ContactTest\Entity\ContactTest'                      => __DIR__ . '/test/ContactTest/Entity/ContactTest.php',
    'ContactTest\Controller\CommandControllerFactoryTest' =>
    __DIR__ . '/test/ContactTest/Controller/CommandControllerFactoryTest.php',
    'ContactTest\Controller\CommandControllerTest'        =>
    __DIR__ . '/test/ContactTest/Controller/CommandControllerTest.php',
    'Contact\Module'                                      => __DIR__ . '/Module.php',
);
