<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contact\Service\Command'                     => __DIR__ . '/src/Contact/Service/Command.php',
    'Contact\Service\CommandFactory'              => __DIR__ . '/src/Contact/Service/CommandFactory.php',
    'Contact\Mapper\Db\Command'                   => __DIR__ . '/src/Contact/Mapper/Db/Command.php',
    'Contact\Feature\CommandInterface'            => __DIR__ . '/src/Contact/Feature/CommandInterface.php',
    'Contact\Form\CreateFactory'                  => __DIR__ . '/src/Contact/Form/CreateFactory.php',
    'Contact\Entity\Contact'                      => __DIR__ . '/src/Contact/Entity/Contact.php',
    'Contact\Listener\Aggregate'                  => __DIR__ . '/src/Contact/Listener/Aggregate.php',
    'Contact\Controller\CommandControllerFactory' => __DIR__ . '/src/Contact/Controller/CommandControllerFactory.php',
    'Contact\Controller\CommandController'        => __DIR__ . '/src/Contact/Controller/CommandController.php',
    'Contact\Module'                              => __DIR__ . '/Module.php',
);
