<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ContentManager\Service\Query'                             => __DIR__ . '/src/ContentManager/Service/Query.php',
    'ContentManager\Service\QueryFactory'                      =>
    __DIR__ . '/src/ContentManager/Service/QueryFactory.php',
    'ContentManager\Mapper\Db\Query'                           => __DIR__ . '/src/ContentManager/Mapper/Db/Query.php',
    'ContentManager\DomainManager\ProviderInterface'           =>
    __DIR__ . '/src/ContentManager/DomainManager/ProviderInterface.php',
    'ContentManager\DomainManager\Factory'                     =>
    __DIR__ . '/src/ContentManager/DomainManager/Factory.php',
    'ContentManager\Feature\QueryInterface'                    =>
    __DIR__ . '/src/ContentManager/Feature/QueryInterface.php',
    'ContentManager\Entity\NullPage'                           => __DIR__ . '/src/ContentManager/Entity/NullPage.php',
    'ContentManager\Entity\Page'                               => __DIR__ . '/src/ContentManager/Entity/Page.php',
    'ContentManager\Controller\QueryControllerFactory'         =>
    __DIR__ . '/src/ContentManager/Controller/QueryControllerFactory.php',
    'ContentManager\Controller\QueryController'                =>
    __DIR__ . '/src/ContentManager/Controller/QueryController.php',
    'ContentManagerTest\Bootstrap'                             => __DIR__ . '/test/Bootstrap.php',
    'ContentManagerTest\Service\QueryTest'                     =>
    __DIR__ . '/test/ContentManagerTest/Service/QueryTest.php',
    'ContentManagerTest\Service\QueryFactoryTest'              =>
    __DIR__ . '/test/ContentManagerTest/Service/QueryFactoryTest.php',
    'ContentManagerTest\Mapper\Db\QueryTest'                   =>
    __DIR__ . '/test/ContentManagerTest/Mapper/Db/QueryTest.php',
    'ContentManagerTest\Service\FactoryTest'                   =>
    __DIR__ . '/test/ContentManagerTest/DomainManager/FactoryTest.php',
    'ContentManagerTest\Entity\NullPageTest'                   =>
    __DIR__ . '/test/ContentManagerTest/Entity/NullPageTest.php',
    'ContentManagerTest\Entity\PageTest'                       =>
    __DIR__ . '/test/ContentManagerTest/Entity/PageTest.php',
    'ContentManagerTest\Controller\QueryControllerFactoryTest' =>
    __DIR__ . '/test/ContentManagerTest/Controller/QueryControllerFactoryTest.php',
    'ContentManagerTest\Controller\QueryControllerTest'        =>
    __DIR__ . '/test/ContentManagerTest/Controller/QueryControllerTest.php',
    'ContentManager\Module'                                    => __DIR__ . '/Module.php',
);
