<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ContentManager\Service\Query'                     => __DIR__ . '/src/ContentManager/Service/Query.php',
    'ContentManager\Service\QueryFactory'              => __DIR__ . '/src/ContentManager/Service/QueryFactory.php',
    'ContentManager\Mapper\Db\Query'                   => __DIR__ . '/src/ContentManager/Mapper/Db/Query.php',
    'ContentManager\Feature\QueryInterface'            => __DIR__ . '/src/ContentManager/Feature/QueryInterface.php',
    'ContentManager\Entity\NullPage'                   => __DIR__ . '/src/ContentManager/Entity/NullPage.php',
    'ContentManager\Entity\Page'                       => __DIR__ . '/src/ContentManager/Entity/Page.php',
    'ContentManager\Controller\QueryControllerFactory' =>
    __DIR__ . '/src/ContentManager/Controller/QueryControllerFactory.php',
    'ContentManager\Controller\QueryController'        =>
    __DIR__ . '/src/ContentManager/Controller/QueryController.php',
    'ContentManager\Module'                            => __DIR__ . '/Module.php',
);
