<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MamuzApplicationTest\Bootstrap'                             => __DIR__ . '/test/Bootstrap.php',
    'MamuzApplicationTest\Controller\IndexControllerTest'        =>
    __DIR__ . '/test/MamuzApplicationTest/Controller/IndexControllerTest.php',
    'MamuzApplicationTest\Filter\MailMessageTest'                =>
    __DIR__ . '/test/MamuzApplicationTest/Filter/MailMessageTest.php',
    'MamuzApplicationTest\Listener\AggregateTest'                =>
    __DIR__ . '/test/MamuzApplicationTest/Listener/AggregateTest.php',
    'MamuzApplicationTest\Navigation\DefaultFactoryTest'         =>
    __DIR__ . '/test/MamuzApplicationTest/Navigation/DefaultFactoryTest.php',
    'MamuzApplicationTest\Navigation\ProductOwnerFactoryTest'    =>
    __DIR__ . '/test/MamuzApplicationTest/Navigation/ProductOwnerFactoryTest.php',
    'MamuzApplicationTest\Options\MailTest'                      =>
    __DIR__ . '/test/MamuzApplicationTest/Options/MailTest.php',
    'MamuzApplicationTest\Service\AggregateFactoryTest'          =>
    __DIR__ . '/test/MamuzApplicationTest/Listener/AggregateFactoryTest.php',
    'MamuzApplicationTest\Service\ContactMailFactoryTest'        =>
    __DIR__ . '/test/MamuzApplicationTest/Service/ContactMailFactoryTest.php',
    'MamuzApplicationTest\Service\ErrorHandlingFactoryTest'      =>
    __DIR__ . '/test/MamuzApplicationTest/Service/ErrorHandlingFactoryTest.php',
    'MamuzApplicationTest\Service\ErrorHandlingTest'             =>
    __DIR__ . '/test/MamuzApplicationTest/Service/ErrorHandlingTest.php',
    'MamuzApplicationTest\Service\FactoryTest'                   =>
    __DIR__ . '/test/MamuzApplicationTest/PluginManager/FactoryTest.php',
    'MamuzApplicationTest\Service\LogFactoryTest'                =>
    __DIR__ . '/test/MamuzApplicationTest/Service/LogFactoryTest.php',
    'MamuzApplicationTest\Service\MailTest'                      =>
    __DIR__ . '/test/MamuzApplicationTest/Service/MailTest.php',
    'MamuzApplicationTest\Service\OutputCacheFactoryTest'        =>
    __DIR__ . '/test/MamuzApplicationTest/Service/OutputCacheFactoryTest.php',
    'MamuzApplicationTest\Service\OutputCacheTest'               =>
    __DIR__ . '/test/MamuzApplicationTest/Service/OutputCacheTest.php',
    'MamuzApplicationTest\Service\ServiceLocatorInitializerTest' =>
    __DIR__ . '/test/MamuzApplicationTest/PluginManager/ServiceLocatorInitializerTest.php',
    'MamuzApplicationTest\View\Helper\AutoVersionFactoryTest'    =>
    __DIR__ . '/test/MamuzApplicationTest/View/Helper/AutoVersionFactoryTest.php',
    'MamuzApplicationTest\View\Helper\AutoVersionTest'           =>
    __DIR__ . '/test/MamuzApplicationTest/View/Helper/AutoVersionTest.php',
    'MamuzApplicationTest\View\Helper\ItemTest'                  =>
    __DIR__ . '/test/MamuzApplicationTest/View/Helper/Navigation/ItemTest.php',
    'MamuzApplication\Controller\IndexController'                =>
    __DIR__ . '/src/MamuzApplication/Controller/IndexController.php',
    'MamuzApplication\Filter\MailMessage'                        =>
    __DIR__ . '/src/MamuzApplication/Filter/MailMessage.php',
    'MamuzApplication\Listener\Aggregate'                        =>
    __DIR__ . '/src/MamuzApplication/Listener/Aggregate.php',
    'MamuzApplication\Listener\AggregateFactory'                 =>
    __DIR__ . '/src/MamuzApplication/Listener/AggregateFactory.php',
    'MamuzApplication\Module'                                    => __DIR__ . '/Module.php',
    'MamuzApplication\Navigation\DefaultFactory'                 =>
    __DIR__ . '/src/MamuzApplication/Navigation/DefaultFactory.php',
    'MamuzApplication\Navigation\ProductOwnerFactory'            =>
    __DIR__ . '/src/MamuzApplication/Navigation/ProductOwnerFactory.php',
    'MamuzApplication\Options\Mail'                              => __DIR__ . '/src/MamuzApplication/Options/Mail.php',
    'MamuzApplication\Options\MailInterface'                     =>
    __DIR__ . '/src/MamuzApplication/Options/MailInterface.php',
    'MamuzApplication\PluginManager\Factory'                     =>
    __DIR__ . '/src/MamuzApplication/PluginManager/Factory.php',
    'MamuzApplication\PluginManager\ProviderInterface'           =>
    __DIR__ . '/src/MamuzApplication/PluginManager/ProviderInterface.php',
    'MamuzApplication\PluginManager\ServiceLocatorInitializer'   =>
    __DIR__ . '/src/MamuzApplication/PluginManager/ServiceLocatorInitializer.php',
    'MamuzApplication\Service\ContactMailFactory'                =>
    __DIR__ . '/src/MamuzApplication/Service/ContactMailFactory.php',
    'MamuzApplication\Service\ErrorHandling'                     =>
    __DIR__ . '/src/MamuzApplication/Service/ErrorHandling.php',
    'MamuzApplication\Service\ErrorHandlingFactory'              =>
    __DIR__ . '/src/MamuzApplication/Service/ErrorHandlingFactory.php',
    'MamuzApplication\Service\Feature\ExceptionLoggerInterface'  =>
    __DIR__ . '/src/MamuzApplication/Service/Feature/ExceptionLoggerInterface.php',
    'MamuzApplication\Service\Feature\MailObjectInterface'       =>
    __DIR__ . '/src/MamuzApplication/Service/Feature/MailObjectInterface.php',
    'MamuzApplication\Service\Feature\OutputCacheInterface'      =>
    __DIR__ . '/src/MamuzApplication/Service/Feature/OutputCacheInterface.php',
    'MamuzApplication\Service\LogFactory'                        =>
    __DIR__ . '/src/MamuzApplication/Service/LogFactory.php',
    'MamuzApplication\Service\Mail'                              => __DIR__ . '/src/MamuzApplication/Service/Mail.php',
    'MamuzApplication\Service\OutputCache'                       =>
    __DIR__ . '/src/MamuzApplication/Service/OutputCache.php',
    'MamuzApplication\Service\OutputCacheFactory'                =>
    __DIR__ . '/src/MamuzApplication/Service/OutputCacheFactory.php',
    'MamuzApplication\View\Helper\AutoVersion'                   =>
    __DIR__ . '/src/MamuzApplication/View/Helper/AutoVersion.php',
    'MamuzApplication\View\Helper\AutoVersionFactory'            =>
    __DIR__ . '/src/MamuzApplication/View/Helper/AutoVersionFactory.php',
    'MamuzApplication\View\Helper\Navigation\Item'               =>
    __DIR__ . '/src/MamuzApplication/View/Helper/Navigation/Item.php',
);
