<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'mamuz-plugin/googleanalytics'  => __DIR__ . '/view/mamuz-plugin/googleanalytics.phtml',
    'mamuz-application/index/index' => __DIR__ . '/view/mamuz-application/index/index.phtml',
    'mamuz-mail/contact/body'       => __DIR__ . '/view/mamuz-mail/contact/body.phtml',
    'mamuz-mail/contact/subject'    => __DIR__ . '/view/mamuz-mail/contact/subject.phtml',
    'mamuz-layout/footer'           => __DIR__ . '/view/mamuz-layout/footer.phtml',
    'mamuz-layout/header'           => __DIR__ . '/view/mamuz-layout/header.phtml',
    'mamuz-layout/layout'           => __DIR__ . '/view/mamuz-layout/layout.phtml',
    'mamuz-error/404'               => __DIR__ . '/view/mamuz-error/404.phtml',
    'mamuz-error/index'             => __DIR__ . '/view/mamuz-error/index.phtml',
);
