<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Service\LogFactory'                       => __DIR__ . '/src/Application/Service/LogFactory.php',
    'Application\Service\ErrorHandlingFactory'             =>
    __DIR__ . '/src/Application/Service/ErrorHandlingFactory.php',
    'Application\Service\Feature\MailObjectInterface'      =>
    __DIR__ . '/src/Application/Service/Feature/MailObjectInterface.php',
    'Application\Service\Feature\ExceptionLoggerInterface' =>
    __DIR__ . '/src/Application/Service/Feature/ExceptionLoggerInterface.php',
    'Application\Service\ErrorHandling'                    => __DIR__ . '/src/Application/Service/ErrorHandling.php',
    'Application\Service\ContactMailFactory'               =>
    __DIR__ . '/src/Application/Service/ContactMailFactory.php',
    'Application\Service\Mail'                             => __DIR__ . '/src/Application/Service/Mail.php',
    'Application\Listener\Aggregate'                       => __DIR__ . '/src/Application/Listener/Aggregate.php',
    'Application\Options\MailInterface'                    => __DIR__ . '/src/Application/Options/MailInterface.php',
    'Application\Options\Mail'                             => __DIR__ . '/src/Application/Options/Mail.php',
    'Application\Filter\MailMessage'                       => __DIR__ . '/src/Application/Filter/MailMessage.php',
    'Application\Controller\IndexController'               =>
    __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Module'                                   => __DIR__ . '/Module.php',
);
