<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApplicationTest\Bootstrap'                             => __DIR__ . '/test/Bootstrap.php',
    'ApplicationTest\Controller\IndexControllerTest'        =>
    __DIR__ . '/test/ApplicationTest/Controller/IndexControllerTest.php',
    'ApplicationTest\Filter\MailMessageTest'                =>
    __DIR__ . '/test/ApplicationTest/Filter/MailMessageTest.php',
    'ApplicationTest\Listener\AggregateTest'                =>
    __DIR__ . '/test/ApplicationTest/Listener/AggregateTest.php',
    'ApplicationTest\Options\MailTest'                      => __DIR__ . '/test/ApplicationTest/Options/MailTest.php',
    'ApplicationTest\Service\ContactMailFactoryTest'        =>
    __DIR__ . '/test/ApplicationTest/Service/ContactMailFactoryTest.php',
    'ApplicationTest\Service\ErrorHandlingFactoryTest'      =>
    __DIR__ . '/test/ApplicationTest/Service/ErrorHandlingFactoryTest.php',
    'ApplicationTest\Service\ErrorHandlingTest'             =>
    __DIR__ . '/test/ApplicationTest/Service/ErrorHandlingTest.php',
    'ApplicationTest\Service\FactoryTest'                   =>
    __DIR__ . '/test/ApplicationTest/PluginManager/FactoryTest.php',
    'ApplicationTest\Service\LogFactoryTest'                =>
    __DIR__ . '/test/ApplicationTest/Service/LogFactoryTest.php',
    'ApplicationTest\Service\MailTest'                      => __DIR__ . '/test/ApplicationTest/Service/MailTest.php',
    'ApplicationTest\Service\ServiceLocatorInitializerTest' =>
    __DIR__ . '/test/ApplicationTest/PluginManager/ServiceLocatorInitializerTest.php',
    'ApplicationTest\View\Helper\AutoVersionFactoryTest'    =>
    __DIR__ . '/test/ApplicationTest/View/Helper/AutoVersionFactoryTest.php',
    'ApplicationTest\View\Helper\AutoVersionTest'           =>
    __DIR__ . '/test/ApplicationTest/View/Helper/AutoVersionlTest.php',
    'Application\Controller\IndexController'                =>
    __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Filter\MailMessage'                        => __DIR__ . '/src/Application/Filter/MailMessage.php',
    'Application\Listener\Aggregate'                        => __DIR__ . '/src/Application/Listener/Aggregate.php',
    'Application\Module'                                    => __DIR__ . '/Module.php',
    'Application\Options\Mail'                              => __DIR__ . '/src/Application/Options/Mail.php',
    'Application\Options\MailInterface'                     => __DIR__ . '/src/Application/Options/MailInterface.php',
    'Application\PluginManager\Factory'                     => __DIR__ . '/src/Application/PluginManager/Factory.php',
    'Application\PluginManager\ProviderInterface'           =>
    __DIR__ . '/src/Application/PluginManager/ProviderInterface.php',
    'Application\PluginManager\ServiceLocatorInitializer'   =>
    __DIR__ . '/src/Application/PluginManager/ServiceLocatorInitializer.php',
    'Application\Service\ContactMailFactory'                =>
    __DIR__ . '/src/Application/Service/ContactMailFactory.php',
    'Application\Service\ErrorHandling'                     => __DIR__ . '/src/Application/Service/ErrorHandling.php',
    'Application\Service\ErrorHandlingFactory'              =>
    __DIR__ . '/src/Application/Service/ErrorHandlingFactory.php',
    'Application\Service\Feature\ExceptionLoggerInterface'  =>
    __DIR__ . '/src/Application/Service/Feature/ExceptionLoggerInterface.php',
    'Application\Service\Feature\MailObjectInterface'       =>
    __DIR__ . '/src/Application/Service/Feature/MailObjectInterface.php',
    'Application\Service\LogFactory'                        => __DIR__ . '/src/Application/Service/LogFactory.php',
    'Application\Service\Mail'                              => __DIR__ . '/src/Application/Service/Mail.php',
    'Application\View\Helper\AutoVersion'                   => __DIR__ . '/src/Application/View/Helper/AutoVersion.php',
    'Application\View\Helper\AutoVersionFactory'            =>
    __DIR__ . '/src/Application/View/Helper/AutoVersionFactory.php',
);
