<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Listener\Aggregate'           => __DIR__ . '/src/Application/Listener/Aggregate.php',
    'Application\Service\LogFactory'           => __DIR__ . '/src/Application/Service/LogFactory.php',
    'Application\Service\ErrorHandlingFactory' => __DIR__ . '/src/Application/Service/ErrorHandlingFactory.php',
    'Application\Service\ErrorHandling'        => __DIR__ . '/src/Application/Service/ErrorHandling.php',
    'Application\Controller\IndexController'   => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Module'                       => __DIR__ . '/Module.php',
);
