<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'plugin/twitter'                        => __DIR__ . '/view/plugin/twitter.phtml',
    'plugin/disqus'                         => __DIR__ . '/view/plugin/disqus.phtml',
    'plugin/googleanalytics'                => __DIR__ . '/view/plugin/googleanalytics.phtml',
    'layout/footer'                         => __DIR__ . '/view/layout/footer.phtml',
    'layout/header'                         => __DIR__ . '/view/layout/header.phtml',
    'layout/layout'                         => __DIR__ . '/view/layout/layout.phtml',
    'mamuz-contact/command/create'          => __DIR__ . '/view/mamuz-contact/command/create.phtml',
    'mamuz-blog/tag-query/items'            => __DIR__ . '/view/mamuz-blog/tag-query/items.phtml',
    'mamuz-blog/post-query/published-post'  => __DIR__ . '/view/mamuz-blog/post-query/published-post.phtml',
    'mamuz-blog/post-query/published-posts' => __DIR__ . '/view/mamuz-blog/post-query/published-posts.phtml',
    'mail/contact/body'                     => __DIR__ . '/view/mail/contact/body.phtml',
    'mail/contact/subject'                  => __DIR__ . '/view/mail/contact/subject.phtml',
    'error/404'                             => __DIR__ . '/view/error/404.phtml',
    'error/index'                           => __DIR__ . '/view/error/index.phtml',
    'application/index/index'               => __DIR__ . '/view/application/index/index.phtml',
);
