<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only"><?php echo $this->translate('Toggle navigation'); ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="Practices, Principles and Patterns of Web-Development">
                <img alt="mamuz' coding blog" src="/img/logo.png" />
                <span>mamuz' coding blog</span>
            </a>

        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php
                foreach ($this->navigation('Application\Navigation\Default')->getPages() as $page) {
                    echo $this->navItem($page);
                }
                ?>
                <li class="visible-xs"><a target="_blank" href="/feed">RSS</a></li>
            </ul>
            <div class="navbar-right">
                <a target="_blank" class="btn hidden-xs" href="/feed" title="RSS"><i class="fa fa-rss fa-lg"></i></a>
            </div>
        </div>
    </div>
</nav>
