<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" title="Marco Muths"><img src="img/logo.png" height="30" /></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php
                foreach ($this->navigation('Application\Navigation\Default')->getPages() as $page) {
                    echo $this->navItem($page);
                }
                ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php
                foreach ($this->navigation('Application\Navigation\ProductOwner')->getPages() as $page) {
                    echo $this->navItem($page);
                }
                ?>
            </ul>
            <form class="navbar-form navbar-right navbar-input-group" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="button">Go</button>
                    </span>
                </div>
            </form>
        </div>
    </div>
</nav>
