<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta() . PHP_EOL; ?>
    <?php echo $this->headTitle()->setSeparator(' - ')->prepend("mamuz' coding blog") . PHP_EOL; ?>
    <meta name="description" content="Blog about Practices, Principles and Patterns of Web-Development">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
</head>
<body style="background-color: #000">
<div id="wrap">
    <?php echo $this->partial('layout/header'); ?>
    <div class="container">
        <div class="row">
            <div id="main-content" class="col-md-9" role="main">
                <?php echo $this->content; ?>
            </div>
            <div id="sidebar" class="col-md-3 sidenav" role="complementary">
                <?php echo $this->sidebar; ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->partial('layout/footer'); ?>

<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Droid+Sans:400,700">
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/vendor/bootstrap.cyborg.min.css' ?>">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="//yandex.st/highlightjs/8.0/styles/monokai.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath() . $this->autoVersion('/css/base-min.css') ?>">
<?php echo $this->headLink() . PHP_EOL; ?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
<script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script src="//yandex.st/highlightjs/8.0/highlight.min.js"></script>
<script src="<?php echo $this->basePath() . '/js/vendor/jquery.jscroll.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/vendor/ZeroClipboard.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . $this->autoVersion('/js/jquery.initializer.plugin-min.js') ?>"></script>
<?php echo $this->inlineScript() . PHP_EOL; ?>
<?php echo $this->partial('plugin/googleanalytics'); ?>
<script>
    $(document).ready(function () {
        $('body').initializer();
    });
</script>
</body>
</html>
