<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta() . PHP_EOL; ?>
    <?php echo $this->headTitle()->setSeparator(' - ')->prepend('Mamuz') . PHP_EOL; ?>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="<?php echo $this->basePath() . '/css/base.css' ?>">
    <?php echo $this->headLink() . PHP_EOL; ?>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php echo $this->headScript() . PHP_EOL; ?>
    <?php echo $this->partial('plugin/googleanalytics'); ?>
</head>
<body>
<div id="wrap">
    <?php echo $this->partial('layout/header'); ?>
    <div class="container">
        <?php echo $this->content; ?>
    </div>
</div>
<?php echo $this->partial('layout/footer'); ?>
</body>
</html>
