<?php

if (!$this->isTerminal) {
    $this->headTitle()->append($this->translate('Blog'));
    echo '<h1>' . $this->translate('Blog') . '</h1>' . PHP_EOL;
    echo '<div class="scroll-list">' . PHP_EOL;
}

foreach ($this->collection as $entity) {
    echo $this->postPanelShort($entity) . PHP_EOL;
}

echo $this->postPager($this->collection, $this->routeParams) . PHP_EOL;

if (!$this->isTerminal) {
    echo "</div>" . PHP_EOL;
    echo '<div id="sidebar" class="col-md-3" role="complementary">';
    echo $this->tagList();
    echo '</div>';
}
