<?php

if ($this->post) {
    $this->headMeta()->appendName('description', $this->post->getDescription());
    $this->headTitle()->append($this->post->getTitle());
    echo $this->partial('plugin/shareaholic-canvas', array('link' => $this->permaLinkPost($this->post)));
    echo $this->postPanel($this->post) . PHP_EOL;
    echo $this->partial('plugin/disqus', array('id' => $this->hashId($this->post->getId())));
}
