<?php

if (!$this->isTerminal) {
    $this->headTitle()->append($this->translate('Archive'));
    echo '<h1>' . $this->translate('Archive') . '</h1>' . PHP_EOL;
    echo '<div class="scroll-list">' . PHP_EOL;
}

foreach ($this->collection as $entity) {
    echo $this->postPanelShort($entity) . PHP_EOL;
}

echo $this->postPager($this->collection, $this->routeParams) . PHP_EOL;

if (!$this->isTerminal) {
    echo "</div>" . PHP_EOL;
    $this->layout()->setVariable('sidebar', $this->tagList());
}
